"""
Biotech Literature Mining MVP

Purpose:
    Identify scientific publications that mention a biotech product and
    extract supporting evidence from the literature.

Why:
    Biotech companies often use publication citations to demonstrate product
    credibility. This tool automates the process of finding papers that
    reference a product by name, SKU/catalog number, or manufacturer.

Pipeline:
    1. Product Input
    2. PubMed Search
    3. PMC Full-Text Retrieval
    4. Product Mention Detection
    5. Evidence Extraction
    6. Results Output
"""


from core.pubmed import fetch_pmc_full_text
from core.pubmed import search_pubmed, get_pubmed_abstract
from core.europe_pmc import search_europe_pmc, fetch_europe_pmc_full_text, get_europe_pmc_abstract
from matcher import find_manufacturer_contexts, find_product_manufacturer_evidence
from core.io import get_product_map, load_evidence_input

import pandas as pd


def get_number_of_results(pmids, europe_pmc_results):
    print(f"Number of PubMed results: {len(pmids)}")
    print(f"Number of Europe PMC results: {len(europe_pmc_results)}")


def extract_evidence(
    manufacturer,
    product_name,
    catalog_number,
    product_map,
    context_radius=1,
    pmids=None,
    europe_pmc_results=None,
):
    """
    Collects product-manufacturer evidence from PubMed and Europe PMC
    and exports the results to a CSV file.

    Output schema:
        manufacturer
        product
        matched_alias
        evidence
        match_type
        source
        publication_id
        publication_url

    Parameters:
        manufacturer (str):
            Manufacturer name.

        product_name (str):
            Canonical product name being investigated.

        product_map (dict):
            Alias lookup generated by build_product_alias_map().

        context_radius (int):
            Context window size passed to matcher.

        pmids (list[str] | None):
            PubMed IDs.

        europe_pmc_results (list[dict] | None):
            Europe PMC search results.

        output_path (str):
            CSV destination path.
    """

    pmids = pmids or []
    europe_pmc_results = europe_pmc_results or []

    records = []

    # ----------------------------
    # PubMed evidence
    # ----------------------------
    for pmid in pmids:

        full_text = fetch_pmc_full_text(pmid)

        if not full_text:
            continue

        matches = find_product_manufacturer_evidence(
            full_text,
            catalog_number,
            product_map,
            manufacturer,
            n=context_radius
        )

        for match in matches:

            records.append({
                "manufacturer": manufacturer,
                "product_name": product_name,
                "sku": catalog_number,
                "evidence": match,
                "source": "PMID",
                "publication_id": pmid,
                "publication_url": f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/"
            })

    # ----------------------------
    # Europe PMC evidence
    # ----------------------------
    for result in europe_pmc_results:

        pmcid = result.get("pmcid")

        if not pmcid:
            continue

        full_text = fetch_europe_pmc_full_text(pmcid)

        if not full_text:
            continue

        matches = find_product_manufacturer_evidence(
            full_text,
            catalog_number,
            product_map,
            manufacturer,
            n=context_radius
        )

        for match in matches:

            records.append({
                "manufacturer": manufacturer,
                "product_name": product_name,
                "sku": catalog_number,
                "evidence": match,
                "source": "PMCID",
                "publication_id": pmcid,
                "publication_url": (
                    f"https://europepmc.org/article/PMC/"
                    f"{pmcid.replace('PMC', '')}"
                )
            })

    return records



def export_evidence_to_csv(product_identifier, evidence, output_folder="data/evidence/"):
    # ----------------------------
    # Export
    # ----------------------------
    df = pd.DataFrame(evidence)

    safe_name = product_identifier.lower().replace(" ", "_")
    output_path = f"{output_folder}{safe_name}_evidence.csv"

    df.to_csv(
        output_path,
        index=False,
        encoding="utf-8-sig"
    )

    print(f"Saved {len(df)} evidence records to {output_path}")

    return df



# ----------------------------
# CODE EXECUTION STARTS HERE
# ----------------------------

# manufacturer
manufacturer = "GeneCopoeia"
INPUT_DIR = "data/genecopoeia_pipeline_test.csv"
ALIASES_DIR = "data/cleaned_products/product_aliases.csv"

# example
# {'sku': 'EF013', 
# 'product_name': 'EndoFectin™ Max Transfection Reagent', '
# tokens': ['ef013', 'endofectin', 'max', 'transfection', 'reagent']}
inputs = load_evidence_input(INPUT_DIR)
print("Loaded product inputs")
# for i in inputs:
#     print(i)

# example
# ('mab-00001', 
# ['4', 'cyk4', 'mab', 'ck-4', 'mab-00001', 'ck4', 'k4', 'p19013', 'cytokeratin', 'wsn1', '3851', 'krt4'])
product_map = get_product_map(ALIASES_DIR)
print("Created product map of all products\n")
# print(next(iter(product_map.items())))

# maximum number of publications queries return
max_results = 25
# size of evidence: number of sentences that can surround manufacturer
evidence_size = 1

for item in inputs:
    sku = item["sku"]
    product_name = item["product_name"]
    tokens = item["tokens"]

    pubmed_results = search_pubmed(manufacturer, product_name, sku, tokens, max_results)
    print(f"Searched PubMed for articles containing {manufacturer} and {product_name}")
    europe_results = search_europe_pmc(manufacturer, product_name, sku, tokens, max_results)
    print(f"Searched Europe PMC for articles containing {manufacturer} and {product_name}")

    num_results = get_number_of_results(pubmed_results, europe_results)
    print(f"Found {num_results} articles containing {manufacturer} and {product_name}")

    evidence = extract_evidence(manufacturer,
                                product_name,
                                sku,
                                product_map,
                                evidence_size,
                                pubmed_results, 
                                europe_results)
    print(f"Extracted evidence containing {manufacturer} and {product_name}")

    export_evidence_to_csv(product_name, evidence)
    print(f"Exported evidence for {manufacturer} and {product_name}")
    print("")